package br.fatecsjc.enumerations;

public enum FearNoun {

	alarm_NN,
	apprehension_NN,
	apprehensiveness_NN,
	boding_VBG,
	chill_NN,
	coldheartedness_NN,
	consternation_NN,
	creeps_NNS,
	cruelty_NN,
	diffidence_NN,
	dismay_NN,
	dread_NN,
	fear_NN,
	fearfulness_NN,
	foreboding_VBG,
	fright_NN,
	hardheartedness_NN,
	heartlessness_NN,
	hesitance_NN,
	hesitancy_NN,
	horror_NN,
	hysteria_NN,
	intimidation_NN,
	mercilessness_NN,
	pall_NN,
	panic_NN,
	panic_attack_NN,
	pitilessness_NN,
	premonition_NN,
	presage_NN,
	presentiment_NN,
	ruthlessness_NN,
	scare_NN,
	shadow_NN,
	shyness_NN,
	stage_fright_NN,
	suspense_NN,
	terror_NN,
	timidity_NN,
	timidness_NN,
	timorousness_NN,
	trepidation_NN,
	unassertiveness_NN
}
